#let syntax-names = (
  ".gitattributes": "Git Attributes",
  "prawn": "Ruby",
  "java server page (jsp)": "Java Server Page (JSP)",
  "apache conf": "Apache Conf",
  "python": "Python",
  "emakefile": "Erlang",
  "ninja": "Ninja",
  ".zlogin": "Bourne Again Shell (bash)",
  "builder": "Ruby on Rails",
  "svg": "XML",
  "mime.types": "nginx",
  "ps1": "PowerShell",
  "nims": "Nim",
  "textproto": "Protocol Buffer (TEXT)",
  "json": "JSON",
  "lua": "Lua",
  "meminfo": "MemInfo",
  "todo.txt": "Todo.txt",
  "fshader": "GLSL",
  "cxx": "C++",
  "html (twig)": "HTML (Twig)",
  "stylus": "Stylus",
  "highlight non-printables": "Highlight non-printables",
  "rcall": "GLSL",
  "requirements.in": "Requirements.txt",
  "passwd": "passwd",
  "clojure": "Clojure",
  "rust": "Rust",
  "C": "C++",
  "html.twig": "HTML (Twig)",
  "tsv": "Tab Separated Values",
  "h.in": "CMake C Header",
  "json (terraform)": "JSON (Terraform)",
  "wgsl": "WGSL",
  "ll": "LLVM",
  "_vimrc": "VimL",
  "sshd_config": "SSHD Config",
  "sc": "Scala",
  ".editorconfig": "INI",
  "for": "Fortran (Fixed Form)",
  "FOR": "Fortran (Fixed Form)",
  "FPP": "Fortran (Fixed Form)",
  "bzl": "Python",
  "inf": "INI",
  "cfg": "INI",
  "sls": "Salt State (SLS)",
  "go.mod": "Gomod",
  "mud": "Lisp",
  "html (erlang)": "HTML (Erlang)",
  "arm assembly": "ARM Assembly",
  "Fastfile": "Ruby",
  "pp": "Puppet",
  "rint": "GLSL",
  "cmd-help": "Command Help",
  "authorized_keys": "Authorized Keys",
  "ruby slim": "Ruby Slim",
  ".zshenv": "Bourne Again Shell (bash)",
  "ex": "Elixir",
  "llvm": "LLVM",
  "odin": "Odin",
  "capfile": "Ruby",
  "lsp": "Lisp",
  "typc": "Typst Code",
  "markdown": "Markdown",
  "Brewfile": "Ruby",
  "gfortran build results": "GFortran Build Results",
  "as": "ActionScript",
  "gradle": "Groovy",
  "xml": "XML",
  ".env.production": "DotENV",
  "csv": "Separated Values",
  "typ": "Typst Markup",
  "vert": "GLSL",
  "mk": "Makefile",
  "xslt": "XML",
  "git attributes": "Git Attributes",
  ".env.example": "DotENV",
  "html.j2": "HTML (Jinja2)",
  ".gvimrc": "VimL",
  "erlang": "Erlang",
  "http request and response": "HTTP Request and Response",
  "make": "Makefile",
  "sublime-project": "JSON",
  "php5": "PHP",
  "debsources": "debsources",
  "lhs": "Literate Haskell",
  "Snapfile": "Ruby",
  "ls.erb": "LiveScript",
  "html.erb": "HTML (Rails)",
  "htpasswd": "Apache Conf",
  "git-rebase-todo": "Git Rebase Todo",
  "sld": "Lisp",
  ".flaskenv": "DotENV",
  "cabal": "Cabal",
  "edn": "Clojure",
  "cc": "C++",
  "task": "GLSL",
  "Makefile": "Makefile",
  "command help": "Command Help",
  "GNUmakefile": "Makefile",
  "git mailmap": "Git Mailmap",
  "f77": "Fortran (Fixed Form)",
  "gitattributes": "Git Attributes",
  "sql.erb": "SQL (Rails)",
  "re": "Regular Expression",
  "gosum": "Gosum",
  "html.leex": "HTML (EEx)",
  "http": "HTTP Request and Response",
  "5": "Groff/troff",
  "regular expressions (elixir)": "Regular Expressions (Elixir)",
  ".gitlint": "INI",
  "nginx": "nginx",
  "protocol buffer": "Protocol Buffer",
  "pxd": "Python",
  "ruby.rail": "Ruby",
  "markdn": "Markdown",
  "Dockerfile": "Dockerfile",
  "nsis": "NSIS",
  "7": "Groff/troff",
  "xml.j2": "HTML (Jinja2)",
  "opml": "XML",
  "py": "Python",
  "objective-c++": "Objective-C++",
  "sol": "Solidity",
  "Appfile": "Ruby",
  "tese": "GLSL",
  "styl": "Stylus",
  "sublime-completions": "JSON",
  "gd": "GDScript (Godot Engine)",
  "simplecov": "Ruby",
  ".htgroups": "Apache Conf",
  "tsx": "TypeScriptReact",
  "plt": "gnuplot",
  "puppet": "Puppet",
  "h": "Objective-C",
  ".env.prod": "DotENV",
  "cron.d": "Crontab",
  "mboxz": "Email",
  "typescript": "TypeScript",
  "testbox": "TestBox",
  "gitlog": "Git Log",
  "rest": "reStructuredText",
  "git rebase todo": "Git Rebase Todo",
  "livescript": "LiveScript",
  "Podfile": "Ruby",
  "env.sample": "DotENV",
  "rmiss": "GLSL",
  "pipe separated values": "Pipe Separated Values",
  ".envrc": "DotENV",
  "CFG": "INI",
  "cmake c header": "CMake C Header",
  "nix": "Nix",
  "csx": "C#",
  "erb": "HTML (Rails)",
  "htm.j2": "HTML (Jinja2)",
  "gp": "gnuplot",
  "hxx": "C++",
  "dockerfile": "Dockerfile",
  "sbt": "Scala",
  "fsi": "F#",
  ".env.default": "DotENV",
  "rgen": "GLSL",
  "nsh": "NSIS",
  "htc": "JavaScript",
  "viml": "VimL",
  "c": "C",
  "rpy": "Python",
  "vpy": "Python",
  ".bash_profile": "Bourne Again Shell (bash)",
  "gnu": "gnuplot",
  "jbuilder": "Ruby",
  "racket": "Racket",
  "ssh crypto": "SSH Crypto",
  "3": "Groff/troff",
  "org": "orgmode",
  "css": "CSS",
  "pm": "Perl",
  "tcl": "Tcl",
  "cmd": "Batch File",
  "vyper": "Vyper",
  ".env.dev": "DotENV",
  "env": "DotENV",
  "INI": "INI",
  "pascal": "Pascal",
  "plot": "gnuplot",
  "fcgi": "Ruby",
  "exs": "Elixir",
  "Slakefile": "LiveScript",
  "batch file": "Batch File",
  "Vagrantfile": "Ruby",
  "diff": "Diff",
  "cmakecommands": "CMakeCommands",
  "Scanfile": "Ruby",
  "fs": "GLSL",
  "hrl": "Erlang",
  ".bash_aliases": "Bourne Again Shell (bash)",
  "vimhelp": "VimHelp",
  "fsx": "F#",
  "namelist": "Fortran Namelist",
  "yml": "YAML",
  "Makefile.in": "Makefile",
  "INF": "INI",
  "git commit": "Git Commit",
  "pxd.in": "Python",
  "HTGROUPS": "Apache Conf",
  "nsdinc": "NSIS",
  "rxml": "Ruby on Rails",
  "vhdl": "VHDL",
  "mli": "OCaml",
  "reg": "INI",
  "REG": "INI",
  "php": "PHP",
  "F": "Fortran (Fixed Form)",
  ".htpasswd": "Apache Conf",
  "DOT": "Graphviz (DOT)",
  "pyx.in": "Python",
  "zig": "Zig",
  "erl": "Erlang",
  ".env.template": "DotENV",
  "8": "Groff/troff",
  "vh": "SystemVerilog",
  "typst code": "Typst Code",
  "R": "R",
  ".env.sample": "DotENV",
  ".nvimrc": "VimL",
  "ipp": "C++",
  "envvars": "Apache Conf",
  "md": "Markdown",
  "cmake c++ header": "CMake C++ Header",
  "rhtml": "HTML (Rails)",
  "Guardfile": "Ruby",
  "pip": "Requirements.txt",
  "proto.text": "Protocol Buffer (TEXT)",
  "hgrc": "INI",
  "graphqls": "GraphQL",
  "known_hosts.old": "Known Hosts",
  "elm compile messages": "Elm Compile Messages",
  "s": "ARM Assembly",
  ".env.testing": "DotENV",
  "Deliverfile": "Ruby",
  "yasm": "x86_64 Assembly",
  "f03": "Fortran (Modern)",
  "c++": "C++",
  "typst": "Typst Markup",
  "ini": "INI",
  "orgmode": "orgmode",
  "resolv": "resolv",
  "cfc": "CFML",
  "F90": "Fortran (Modern)",
  ".git": "Git Link",
  "sconstruct": "Python",
  "Gopkg.lock": "TOML",
  "vy": "Vyper",
  "commands-builtin-shell-bash": "commands-builtin-shell-bash",
  "uv.lock": "TOML",
  "bib": "BibTeX",
  "sql": "SQL",
  "idr": "Idris",
  "css.less": "Less",
  "sublime-menu": "JSON",
  "js.erb": "JavaScript (Rails)",
  "mts": "TypeScript",
  "podspec": "Ruby",
  "multimarkdown": "MultiMarkdown",
  "x86_64 assembly": "x86_64 Assembly",
  "awk": "AWK",
  "ads": "Ada",
  "dtml": "XML",
  "Rakefile": "Ruby",
  "fish": "Fish",
  ".HTACCESS": "Apache Conf",
  "mbx": "Email",
  "jinja": "Jinja2",
  "html (asp)": "HTML (ASP)",
  "dart": "Dart",
  "less": "Less",
  "cpp": "C++",
  "escript": "Erlang",
  "bnsh": "NSIS",
  "html (rails)": "HTML (Rails)",
  "h++": "C++",
  "php7": "PHP",
  "Appraisals": "Ruby",
  "bnsi": "NSIS",
  "ada": "Ada",
  "prototxt": "Protocol Buffer (TEXT)",
  "gv": "Graphviz (DOT)",
  "lisp": "Lisp",
  "vht": "VHDL",
  "r": "R",
  "idris": "Idris",
  "graphviz (dot)": "Graphviz (DOT)",
  "manpage": "Manpage",
  "attributes": "Git Attributes",
  "pyx": "Python",
  "pyw": "Python",
  "sh": "Bourne Again Shell (bash)",
  "java properties": "Java Properties",
  "shell-unix-generic": "Shell-Unix-Generic",
  "mak": "Makefile",
  "zsh": "Bourne Again Shell (bash)",
  "purescript": "PureScript",
  ".profile": "Bourne Again Shell (bash)",
  "lng": "INI",
  "Cargo.lock": "TOML",
  ".HTPASSWD": "Apache Conf",
  "S": "ARM Assembly",
  "4": "Groff/troff",
  "perl": "Perl",
  "known hosts": "Known Hosts",
  "clisp": "Lisp",
  "Berksfile": "Ruby",
  "Cakefile": "CoffeeScript",
  "javascript (babel)": "JavaScript (Babel)",
  "erbsql": "SQL (Rails)",
  "hh": "C++",
  "config.ru": "Ruby",
  "rahit": "GLSL",
  "9": "Groff/troff",
  "xhtml.j2": "HTML (Jinja2)",
  "sublime-theme": "JSON",
  "fsh": "GLSL",
  "rkt": "Racket",
  "tfvars": "Terraform",
  "Pipfile": "TOML",
  "ocamlyacc": "OCamlyacc",
  "cmakecache": "CMakeCache",
  "dockerfile (with bash)": "Dockerfile (with bash)",
  "ash": "Bourne Again Shell (bash)",
  "hosts": "Hosts File",
  "ss": "Lisp",
  "rng": "XML",
  "f90": "Fortran (Modern)",
  "cjs": "JavaScript (Babel)",
  "kt": "Kotlin",
  "regular expressions (python)": "Regular Expressions (Python)",
  "protodevel": "Protocol Buffer",
  "show-nonprintable": "Highlight non-printables",
  ".zshrc": "Bourne Again Shell (bash)",
  "cl": "Lisp",
  "cpy": "Python",
  "javascript (rails)": "JavaScript (Rails)",
  ".env.development": "DotENV",
  "eml": "Email",
  "makefile.am": "Makefile",
  "makefile": "Makefile",
  "hpp": "C++",
  "crontab": "Crontab",
  ".gitconfig": "Git Config",
  "plain text": "Plain Text",
  "fstab": "fstab",
  "Makefile.am": "Makefile",
  "rjs": "Ruby",
  "f": "Fortran (Fixed Form)",
  "rake": "Ruby",
  "vs": "GLSL",
  "comp": "GLSL",
  "wiki": "MediaWiki",
  "php4": "PHP",
  "pbtxt": "Protocol Buffer (TEXT)",
  "v": "Verilog",
  "sublime-syntax": "YAML",
  "es6": "JavaScript (Babel)",
  "graphql": "GraphQL",
  "syslog": "syslog",
  "phtml": "PHP",
  "j2": "Jinja2",
  "gdscript (godot engine)": "GDScript (Godot Engine)",
  "powershell": "PowerShell",
  "coffeescript": "CoffeeScript",
  "ad": "AsciiDoc (Asciidoctor)",
  "htaccess": "Apache Conf",
  "coffee.erb": "CoffeeScript",
  ".pylintrc": "INI",
  "svlt": "Svelte",
  "HTPASSWD": "Apache Conf",
  "rego": "Rego",
  "slim": "Ruby Slim",
  "regular expression": "Regular Expression",
  "resolv.conf": "resolv",
  "private key": "Private Key",
  "literate haskell": "Literate Haskell",
  "log": "log",
  "Jenkinsfile": "Groovy",
  ".bash_variables": "Bourne Again Shell (bash)",
  "twig": "HTML (Twig)",
  "kts": "Kotlin",
  "COMMIT_EDITMSG": "Git Commit",
  "regular expressions (php)": "Regular Expressions (PHP)",
  "tesc": "GLSL",
  "regular expressions (javascript)": "Regular Expressions (Javascript)",
  "cpuinfo": "CpuInfo",
  "nsi": "NSIS",
  "systemverilog": "SystemVerilog",
  "gvy": "Groovy",
  "properties": "Java Properties",
  "asciidoc (asciidoctor)": "AsciiDoc (Asciidoctor)",
  "fortran namelist": "Fortran Namelist",
  "mediawikerpanel": "MediawikerPanel",
  "sublime-macro": "JSON",
  ".env.local": "DotENV",
  "javascript": "JavaScript",
  "m": "Objective-C",
  "htm": "HTML",
  "f#": "F#",
  "pc": "Perl",
  "haml": "Ruby Haml",
  "dml": "SQL",
  "hh.in": "CMake C++ Header",
  "phpt": "PHP",
  "hxx.in": "CMake C++ Header",
  "adb": "Ada",
  "TAG_EDITMSG": "Git Commit",
  "URL": "INI",
  "psm1": "PowerShell",
  "hpp.in": "CMake C++ Header",
  "typescriptreact": "TypeScriptReact",
  "robot": "Robot Framework",
  "cljc": "Clojure",
  "Sconstruct": "Python",
  "PKGBUILD": "Bourne Again Shell (bash)",
  ".zprofile": "Bourne Again Shell (bash)",
  "mediawiki": "MediaWiki",
  "strace": "Strace",
  "js": "JavaScript (Babel)",
  "vshader": "GLSL",
  "libjsonnet": "jsonnet",
  "wikipedia": "MediaWiki",
  "mesh": "GLSL",
  "qmlproject": "QML",
  "_exrc": "VimL",
  ".vimrc": "VimL",
  "sublime-mousemap": "JSON",
  "gitconfig": "Git Config",
  "bibtex": "BibTeX",
  "F77": "Fortran (Fixed Form)",
  "psd1": "PowerShell",
  "gvimrc": "VimL",
  "sublime-color-scheme": "JSON",
  "c#": "C#",
  "d": "D",
  "xhtml": "HTML",
  "mly": "OCamlyacc",
  "yaws": "HTML (Erlang)",
  "el": "Lisp",
  "rb": "Ruby",
  "rbx": "Ruby",
  "fastcgi_params": "nginx",
  "jsx": "JavaScript (Babel)",
  "objective-c": "Objective-C",
  "cargo build results": "Cargo Build Results",
  "HTACCESS": "Apache Conf",
  "sublime-build": "JSON",
  "cson": "CoffeeScript",
  "applescript": "AppleScript",
  "ruby haml": "Ruby Haml",
  "ocamllex": "OCamllex",
  "restructuredtext": "reStructuredText",
  "Rprofile": "R",
  "sources.list": "debsources",
  "ruby on rails": "Ruby on Rails",
  "ebuild": "Bourne Again Shell (bash)",
  ".mailmap": "Git Mailmap",
  "gs": "GLSL",
  "dot": "Graphviz (DOT)",
  "mm": "Objective-C++",
  "bat": "Batch File",
  "Pipfile.lock": "JSON",
  "dmd output": "DMD Output",
  "scala": "Scala",
  "tex": "LaTeX",
  "php3": "PHP",
  "groff/troff": "Groff/troff",
  "tld": "XML",
  "h++.in": "CMake C++ Header",
  "elm documentation": "Elm Documentation",
  "vue component": "Vue Component",
  "typst build results": "Typst Build Results",
  "ts": "TypeScript",
  "pmc": "Perl",
  "git ignore": "Git Ignore",
  "protocol buffer (text)": "Protocol Buffer (TEXT)",
  "ml": "OCaml",
  ".exrc": "VimL",
  "patch": "Diff",
  "javadoc": "Javadoc",
  "gpr": "Ada",
  "2": "Groff/troff",
  "jsonnet": "jsonnet",
  "babel": "JavaScript (Babel)",
  "yaml": "YAML",
  "css.liquid": "CSS",
  "solidity": "Solidity",
  "py3": "Python",
  "ddl": "SQL",
  "MERGE_MSG": "Git Commit",
  "actionscript": "ActionScript",
  ".htaccess": "Apache Conf",
  "cr": "Crystal",
  "troff": "Groff/troff",
  "gypi": "Python",
  "vhd": "VHDL",
  "sublime-commands": "JSON",
  "cmake": "CMake",
  "p": "Pascal",
  "rabl": "Ruby",
  "crystal": "Crystal",
  ".env.test.local": "DotENV",
  "vimrc": "VimL",
  "email": "Email",
  "semi-colon separated values": "Semi-Colon Separated Values",
  ".env.dist": "DotENV",
  "cfml script (tags)": "CFML Script (Tags)",
  "ssh config": "SSH Config",
  "sql (rails)": "SQL (Rails)",
  ".env.staging": "DotENV",
  "groff": "Groff/troff",
  "hosts file": "Hosts File",
  "go.work": "Gomod",
  "sv": "SystemVerilog",
  "svh": "SystemVerilog",
  "nasm": "x86_64 Assembly",
  "pxi": "Python",
  "camlp4": "camlp4",
  "go": "Go",
  "sublime-keymap": "JSON",
  "textile": "Textile",
  "V": "Verilog",
  "fpp": "Fortran (Fixed Form)",
  "fortran (modern)": "Fortran (Modern)",
  "gpl": "gnuplot",
  "nant build file": "NAnt Build File",
  "cfml": "CFML",
  "jsp": "Java Server Page (JSP)",
  "separated values": "Separated Values",
  ".hgrc": "INI",
  "purs": "PureScript",
  "SConstruct": "Python",
  ".env.production.local": "DotENV",
  "pdm.lock": "TOML",
  "hcl": "Terraform",
  "jl": "Julia",
  "poetry.lock": "TOML",
  "authorized_keys2": "Authorized Keys",
  ".Dockerfile": "Dockerfile",
  "uwsgi_params": "nginx",
  "r console": "R Console",
  "kotlin": "Kotlin",
  "sty": "TeX",
  "libsonnet": "jsonnet",
  ".coveragerc": "INI",
  "dotenv": "DotENV",
  "navigational bar vhdl": "Navigational Bar VHDL",
  "svelte": "Svelte",
  "gyp": "Python",
  "latex log": "LaTeX Log",
  "desktop": "INI",
  "mdown": "Markdown",
  "fortran (fixed form)": "Fortran (Fixed Form)",
  "Snakefile": "Python",
  "nim": "Nim",
  "geom": "GLSL",
  "_gvimrc": "VimL",
  "pod": "Perl",
  "latex": "LaTeX",
  "rst": "reStructuredText",
  ".textmate_init": "Bourne Again Shell (bash)",
  "gshader": "GLSL",
  "Thorfile": "Ruby",
  "mtab": "fstab",
  "sshd config": "SSHD Config",
  "F95": "Fortran (Modern)",
  "crypttab": "fstab",
  "vim": "VimL",
  "mll": "OCamllex",
  "known_hosts": "Known Hosts",
  "toml": "TOML",
  "salt state (sls)": "Salt State (SLS)",
  "OCamlMakefile": "Makefile",
  "julia": "Julia",
  "lean 4": "Lean 4",
  "nimble": "Nim",
  "f95": "Fortran (Modern)",
  "done.txt": "Todo.txt",
  "t": "Perl",
  "irbrc": "Ruby",
  "cfm": "CFML",
  "sass": "Sass",
  "css.erb": "CSS",
  "hs": "Haskell",
  "cfml script": "CFML Script",
  "asp": "HTML (ASP)",
  "textpb": "Protocol Buffer (TEXT)",
  "makefile.in": "Makefile",
  ".gitignore": "Git Ignore",
  "navigational bar sv": "Navigational Bar SV",
  ".zlogout": "Bourne Again Shell (bash)",
  "bsh": "Java",
  "xaml": "XML",
  "tf": "Terraform",
  "Emakefile": "Erlang",
  "ssh_config": "SSH Config",
  "di": "D",
  "robot framework": "Robot Framework",
  "cp": "C++",
  "SConscript": "Python",
  "varlink": "varlink",
  "coffee": "CoffeeScript",
  "git log": "Git Log",
  "asa": "ASP",
  "l": "Lisp",
  "pas": "Pascal",
  "rd (r documentation)": "Rd (R Documentation)",
  "groovy": "Groovy",
  "fasl": "Lisp",
  "pyi": "Python",
  "inl": "C++",
  "CMakeLists.txt": "CMake",
  "M": "Objective-C++",
  "html.eex": "HTML (EEx)",
  "F03": "Fortran (Modern)",
  "go.sum": "Gosum",
  "conf": "nginx",
  "proto": "Protocol Buffer",
  "cts": "TypeScript",
  "help": "Command Help",
  "wscript": "Python",
  "gitignore": "Git Ignore",
  "Cheffile": "Ruby",
  "jq": "JQ",
  "F08": "Fortran (Modern)",
  "bazel": "Python",
  "vsh": "GLSL",
  "dpr": "Pascal",
  "thor": "Ruby",
  "openmp (fortran)": "OpenMP (Fortran)",
  ".HTGROUPS": "Apache Conf",
  "conf.erb": "nginx",
  "resource": "Robot Framework",
  "comma separated values": "Comma Separated Values",
  "url": "INI",
  "xsd": "XML",
  "make output": "Make Output",
  ".env.dusk.local": "DotENV",
  "lean": "Lean 4",
  "build": "NAnt Build File",
  "cgi": "Ruby",
  "pb.txt": "Protocol Buffer (TEXT)",
  "exclude": "Git Ignore",
  "sig": "SML",
  "ex.re": "Regular Expressions (Elixir)",
  "verilog": "Verilog",
  "bash": "Bourne Again Shell (bash)",
  ".bashrc": "Bourne Again Shell (bash)",
  "skim": "Ruby Slim",
  "Rantfile": "Ruby",
  "phps": "PHP",
  "cm": "SML",
  "terraform": "Terraform",
  "tml": "TOML",
  "authorized keys": "Authorized Keys",
  "Gemfile": "Ruby",
  "ruby": "Ruby",
  "script editor": "AppleScript",
  "glsl": "GLSL",
  "java": "Java",
  "tfstate": "JSON (Terraform)",
  "f08": "Fortran (Modern)",
  "html": "HTML",
  "gemspec": "Ruby",
  "pxi.in": "Python",
  "qml": "QML",
  "html (jinja2)": "HTML (Jinja2)",
  "zon": "Zig",
  "cls": "TeX",
  "git common": "Git Common",
  "rchit": "GLSL",
  "gnuplot": "gnuplot",
  "shtml": "HTML",
  "scm": "Lisp",
  "elm": "Elm",
  "mac": "x86_64 Assembly",
  "vue": "Vue Component",
  "adp": "HTML (Tcl)",
  "sml": "SML",
  "cs": "C#",
  ".bash_completions": "Bourne Again Shell (bash)",
  "haskell": "Haskell",
  "gomod": "Gomod",
  "scss": "SCSS",
  "sublime-settings": "JSON",
  "tab separated values": "Tab Separated Values",
  "html (eex)": "HTML (EEx)",
  "requirements.txt": "Requirements.txt",
  "env.example": "DotENV",
  "env.template": "DotENV",
  "ssh common": "SSH Common",
  "cljs": "Clojure",
  "rd": "Rd (R Documentation)",
  "matlab": "MATLAB",
  "rss": "XML",
  ".env.defaults": "DotENV",
  "epp": "Puppet",
  "man": "Manpage",
  "jinja2": "Jinja2",
  "tab": "Crontab",
  "git config": "Git Config",
  "typm": "Typst Math",
  "txt": "Plain Text",
  "inc": "x86_64 Assembly",
  ".bash_functions": "Bourne Again Shell (bash)",
  "protobuf": "Protocol Buffer",
  "elixir": "Elixir",
  "group": "group",
  "swift": "Swift",
  "git link": "Git Link",
  "ipynb": "JSON",
  "pl": "Perl",
  "rails": "HTML (Rails)",
  "eclass": "Bourne Again Shell (bash)",
  "asm": "x86_64 Assembly",
  "CMakeCache.txt": "CMakeCache",
  ".bash_logout": "Bourne Again Shell (bash)",
  "gql": "GraphQL",
  "asciidoc": "AsciiDoc (Asciidoctor)",
  "htgroups": "Apache Conf",
  "1": "Groff/troff",
  "6": "Groff/troff",
  "mjs": "JavaScript (Babel)",
  "clj": "Clojure",
  "ls": "LiveScript",
  "ocaml": "OCaml",
  "nginx.conf": "nginx",
  ".gitmodules": "Git Config",
  "rs": "Rust",
  "pub": "Authorized Keys",
  "scgi_params": "nginx",
  ".bash_login": "Bourne Again Shell (bash)",
  "php source": "PHP Source",
  "adoc": "AsciiDoc (Asciidoctor)",
  ".env.test": "DotENV",
  "html (tcl)": "HTML (Tcl)",
  "gsh": "GLSL",
  "mailmap": "Git Mailmap",
  "bourne again shell (bash)": "Bourne Again Shell (bash)",
  "ltx": "LaTeX",
  "msg": "Email",
  ".env": "DotENV",
  ".env.development.local": "DotENV",
  "frag": "GLSL",
  "vho": "VHDL",
)
